ONE - On-device Neural Engine: onert::exec::IExecutors Class Reference
onert::exec::IExecutors Class Reference abstract
Class to gather executors.
#include <IExecutors.h>
Public Member Functions
virtual ~IExecutors ()=default
Virtual IExecutors destructor.
virtual void emplace (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index, std::unique_ptr< IExecutor > exec)=0
virtual IExecutor * at (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index) const =0
IExecutor * entryExecutor () const
virtual uint32_t inputSize () const =0
virtual uint32_t outputSize () const =0
virtual const ir::OperandInfo inputInfo (const ir::IOIndex &index)=0
virtual const ir::OperandInfo outputInfo (const ir::IOIndex &index)=0
virtual void execute (const IODescription &desc)=0
Detailed Description
Class to gather executors.
Definition at line 30 of file IExecutors.h.
Constructor & Destructor Documentation
~IExecutors()
virtual onert::exec::IExecutors::~IExecutors () virtual default
Virtual IExecutors destructor.
Note
Require derived class destructor
Member Function Documentation
at()
virtual IExecutor * onert::exec::IExecutors::at (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index) const pure virtual
Implemented in onert::exec::Executors.
Referenced by entryExecutor(), onert::backend::builtin::kernel::IfLayer::run(), and onert::backend::builtin::kernel::WhileLayer::run().
emplace()
virtual void onert::exec::IExecutors::emplace (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index, std::unique_ptr< IExecutor > exec) pure virtual
Implemented in onert::exec::Executors.
entryExecutor()
IExecutor * onert::exec::IExecutors::entryExecutor () const inline
Definition at line 47 of file IExecutors.h.
{ return at(ir::ModelIndex{0}, ir::SubgraphIndex{0}); }
References at().
Referenced by onert::exec::Executors::execute(), onert::exec::Executors::inputInfo(), onert::exec::Executors::inputSize(), onert::exec::Executors::outputInfo(), and onert::exec::Executors::outputSize().
execute()
virtual void onert::exec::IExecutors::execute (const IODescription & desc) pure virtual
Implemented in onert::exec::Executors.
inputInfo()
virtual const ir::OperandInfo onert::exec::IExecutors::inputInfo (const ir::IOIndex & index) pure virtual
Implemented in onert::exec::Executors.
inputSize()
virtual uint32_t onert::exec::IExecutors::inputSize () const pure virtual
Implemented in onert::exec::Executors.
outputInfo()
virtual const ir::OperandInfo onert::exec::IExecutors::outputInfo (const ir::IOIndex & index) pure virtual
Implemented in onert::exec::Executors.
outputSize()
virtual uint32_t onert::exec::IExecutors::outputSize () const pure virtual
Implemented in onert::exec::Executors.
The documentation for this class was generated from the following file:
runtime/onert/core/include/exec/IExecutors.h