ONE - On-device Neural Engine: onert::exec::Executors Class Reference
onert::exec::Executors Class Reference
Class to gather executors.
#include <Executors.h>
Public Member Functions
Executors (void)=default
Executors (std::unique_ptr< ir::ModelEdges > model_edges)
Executors (const Executors &)=delete
Executors (Executors &&)=default
~Executors ()=default
void emplace (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index, std::unique_ptr< IExecutor > exec)
IExecutor * at (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index) const
uint32_t inputSize () const
uint32_t outputSize () const
const ir::OperandInfo inputInfo (const ir::IOIndex &index)
const ir::OperandInfo outputInfo (const ir::IOIndex &index)
void execute (const IODescription &desc)
Public Member Functions inherited from onert::exec::IExecutors
virtual ~IExecutors ()=default
Virtual IExecutors destructor.
virtual void emplace (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index, std::unique_ptr< IExecutor > exec)=0
virtual IExecutor * at (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index) const =0
IExecutor * entryExecutor () const
virtual uint32_t inputSize () const =0
virtual uint32_t outputSize () const =0
virtual const ir::OperandInfo inputInfo (const ir::IOIndex &index)=0
virtual const ir::OperandInfo outputInfo (const ir::IOIndex &index)=0
virtual void execute (const IODescription &desc)=0
Detailed Description
Class to gather executors.
Definition at line 46 of file Executors.h.
Constructor & Destructor Documentation
Executors() [1/4]
onert::exec::Executors::Executors (void) default
Executors() [2/4]
onert::exec::Executors::Executors (std::unique_ptr< ir::ModelEdges > model_edges) inline
Definition at line 50 of file Executors.h.
{ _model_edges = std::move(model_edges); }
Executors() [3/4]
onert::exec::Executors::Executors (const Executors &) delete
Executors() [4/4]
onert::exec::Executors::Executors (Executors &&) default
~Executors()
onert::exec::Executors::~Executors () default
Member Function Documentation
at()
IExecutor * onert::exec::Executors::at (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index) const virtual
Implements onert::exec::IExecutors.
Definition at line 30 of file Executors.cc.
{
  return _executors.at(std::make_pair(model_index, subg_index)).get();
}
Referenced by inputInfo(), and outputInfo().
emplace()
void onert::exec::Executors::emplace (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index, std::unique_ptr< IExecutor > exec) virtual
Implements onert::exec::IExecutors.
Definition at line 24 of file Executors.cc.
{
  _executors.emplace(std::make_pair(model_index, subg_index), std::move(exec));
}
execute()
void onert::exec::Executors::execute (const IODescription & desc) virtual
Implements onert::exec::IExecutors.
Definition at line 80 of file Executors.cc.
{
  if (_model_edges)
    return executeModels(desc);
  entryExecutor()->execute(desc);
}
References onert::exec::IExecutors::entryExecutor(), and onert::exec::IExecutor::execute().
inputInfo()
const ir::OperandInfo onert::exec::Executors::inputInfo (const ir::IOIndex & index) virtual
Implements onert::exec::IExecutors.
Definition at line 48 of file Executors.cc.
{
  if (_model_edges)
  {
    auto const desc = _model_edges->pkg_inputs[index.value()];
    auto const model_index = std::get<0>(desc);
    auto const subg_index = std::get<1>(desc);
    auto const executor = at(model_index, subg_index);
    auto const input_index = executor->graph().getInputs().at(std::get<2>(desc));
    return executor->graph().operands().at(input_index).info();
  }
  const auto input_index = entryExecutor()->graph().getInputs().at(index);
  return entryExecutor()->graph().operands().at(input_index).info();
}
References onert::util::ObjectManager< Index, Object >::at(), at(), onert::ir::OperandIndexSequence::at(), onert::exec::IExecutors::entryExecutor(), onert::ir::Graph::getInputs(), onert::exec::IExecutor::graph(), and onert::ir::Graph::operands().
inputSize()
uint32_t onert::exec::Executors::inputSize () const virtual
Implements onert::exec::IExecutors.
Definition at line 36 of file Executors.cc.
{
  return _model_edges ? _model_edges->pkg_inputs.size()
                      : entryExecutor()->graph().getInputs().size();
}
References onert::exec::IExecutors::entryExecutor(), onert::ir::Graph::getInputs(), onert::exec::IExecutor::graph(), and onert::ir::OperandIndexSequence::size().
outputInfo()
const ir::OperandInfo onert::exec::Executors::outputInfo (const ir::IOIndex & index) virtual
Implements onert::exec::IExecutors.
Definition at line 64 of file Executors.cc.
{
  if (_model_edges)
  {
    auto const desc = _model_edges->pkg_outputs[index.value()];
    auto const model_index = std::get<0>(desc);
    auto const subg_index = std::get<1>(desc);
    auto const executor = at(model_index, subg_index);
    auto const output_index = executor->graph().getOutputs().at(std::get<2>(desc));
    return executor->graph().operands().at(output_index).info();
  }
  auto output_index = entryExecutor()->graph().getOutputs().at(index);
  return entryExecutor()->graph().operands().at(output_index).info();
}
References onert::util::ObjectManager< Index, Object >::at(), at(), onert::ir::OperandIndexSequence::at(), onert::exec::IExecutors::entryExecutor(), onert::ir::Graph::getOutputs(), onert::exec::IExecutor::graph(), and onert::ir::Graph::operands().
outputSize()
uint32_t onert::exec::Executors::outputSize () const virtual
Implements onert::exec::IExecutors.
Definition at line 42 of file Executors.cc.
{
  return _model_edges ? _model_edges->pkg_outputs.size()
                      : entryExecutor()->graph().getOutputs().size();
}
References onert::exec::IExecutors::entryExecutor(), onert::ir::Graph::getOutputs(), onert::exec::IExecutor::graph(), and onert::ir::OperandIndexSequence::size().
The documentation for this class was generated from the following files:
runtime/onert/core/src/exec/Executors.h
runtime/onert/core/src/exec/Executors.cc